<?php
defined('ABSPATH') || exit;

if(function_exists('acf_add_local_field_group')):

acf_add_local_field_group([
  'key' => 'group_5e5f9a43b6345',
  'title' => 'Ingredient',
  'fields' => [
    [
      'key' => 'field_5e5f9a4a3737f',
      'label' => 'Content',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'placement' => 'top',
      'endpoint' => 0,
    ],
    [
      'key' => 'field_ingredient_description',
      'label' => 'Description',
      'name' => 'description',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
      'delay' => 0,
    ],
    [
      'key' => 'field_ingredient_gallery',
      'label' => 'Gallery',
      'name' => 'gallery',
      'type' => 'gallery',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'return_format' => 'url',
      'preview_size' => 'large',
      'insert' => 'append',
      'library' => 'all',
      'min' => '',
      'max' => '',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ],
    [
      'key' => 'field_5e5f9a6a37382',
      'label' => 'Details',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'placement' => 'top',
      'endpoint' => 0,
    ],
    [
      'key' => 'field_ingredient_unit',
      'label' => 'Unit',
      'name' => 'unit',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '25',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ],
    [
      'key' => 'field_ingredient_macros',
      'label' => 'Macros',
      'name' => 'macros',
      'type' => 'group',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'layout' => 'block',
      'sub_fields' => [
        [
          'key' => 'field_ingredient_macros_calories',
          'label' => 'Calories',
          'name' => 'calories',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '25',
            'class' => '',
            'id' => '',
          ],
          'default_value' => 0,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ],
        [
          'key' => 'field_ingredient_macros_carbs',
          'label' => 'Carbs',
          'name' => 'carbs',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '25',
            'class' => '',
            'id' => '',
          ],
          'default_value' => 0,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ],
        [
          'key' => 'field_ingredient_macros_fats',
          'label' => 'Fats',
          'name' => 'fats',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '25',
            'class' => '',
            'id' => '',
          ],
          'default_value' => 0,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ],
        [
          'key' => 'field_ingredient_macros_proteins',
          'label' => 'Proteins',
          'name' => 'proteins',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '25',
            'class' => '',
            'id' => '',
          ],
          'default_value' => 0,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ],
      ],
    ],
    [
      'key' => 'field_ingredient_rel',
      'label' => 'Recipes',
      'name' => 'related_object',
      'type' => 'relationship',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'post_type' => [
        0 => 'recipe',
      ],
      'taxonomy' => '',
      'filters' => '',
      'elements' => '',
      'min' => '',
      'max' => '',
      'return_format' => 'object',
    ]
  ],
  'location' => [
    [
      [
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'ingredient',
      ],
    ],
  ],
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
]);

endif;