<?php
defined('ABSPATH') || exit;

if(function_exists('acf_add_local_field_group')):

acf_add_local_field_group([
  'key' => 'group_recipe',
  'title' => 'Recipe',
  'fields' => [
    [
      'key' => 'field_recipe_content',
      'label' => 'Content',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'placement' => 'top',
      'endpoint' => 0,
    ],
    [
      'key' => 'field_recipe_description',
      'label' => 'Description',
      'name' => 'description',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
      'delay' => 0,
    ],
    [
      'key' => 'field_recipe_gallery',
      'label' => 'Gallery',
      'name' => 'gallery',
      'type' => 'gallery',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'return_format' => 'array',
      'preview_size' => 'large',
      'insert' => 'append',
      'library' => 'all',
      'min' => '',
      'max' => '',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ],
    [
      'key' => 'field_recipe_details',
      'label' => 'Details',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'placement' => 'top',
      'endpoint' => 0,
    ],
    [
      'key' => 'field_5e5f96fff520a',
      'label' => 'Ingredients',
      'name' => 'ingredients',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => '',
      'sub_fields' => [
        [
          'key' => 'field_recipe_ingredients_ingredient',
          'label' => 'Ingredient',
          'name' => 'ingredient',
          'type' => 'post_object',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '50',
            'class' => '',
            'id' => '',
          ],
          'post_type' => [
            0 => 'ingredient',
          ],
          'taxonomy' => '',
          'allow_null' => 0,
          'multiple' => 0,
          'return_format' => 'object',
          'ui' => 1,
        ],
        [
          'key' => 'field_recipe_ingredients_quantity',
          'label' => 'Quantity',
          'name' => 'quantity',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '25',
            'class' => '',
            'id' => '',
          ],
          'default_value' => 0,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ],
        [
          'key' => 'field_recipe_ingredients_unit',
          'label' => 'Unit',
          'name' => 'unit',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '25',
            'class' => '',
            'id' => '',
          ],
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ],
      ],
    ],
    [
      'key' => 'field_recipe_procedures',
      'label' => 'Procedures',
      'name' => 'procedures',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => '',
      'sub_fields' => [
        [
          'key' => 'field_recipe_procedures_instruction',
          'label' => 'Instruction',
          'name' => 'instruction',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
          ],
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ],
      ],
    ],
    [
      'key' => 'field_recipe_macros',
      'label' => 'Macros',
      'name' => 'macros',
      'type' => 'group',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'layout' => 'block',
      'sub_fields' => [
        [
          'key' => 'field_recipe_macros_calories',
          'label' => 'Calories',
          'name' => 'calories',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '25',
            'class' => '',
            'id' => '',
          ],
          'default_value' => 0,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ],
        [
          'key' => 'field_recipe_macros_carbs',
          'label' => 'Carbs',
          'name' => 'carbs',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '25',
            'class' => '',
            'id' => '',
          ],
          'default_value' => 0,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ],
        [
          'key' => 'field_recipe_macros_fats',
          'label' => 'Fats',
          'name' => 'fats',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '25',
            'class' => '',
            'id' => '',
          ],
          'default_value' => 0,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ],
        [
          'key' => 'field_recipe_macros_proteins',
          'label' => 'Proteins',
          'name' => 'proteins',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => [
            'width' => '25',
            'class' => '',
            'id' => '',
          ],
          'default_value' => 0,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ],
      ],
    ],
    [
      'key' => 'field_recipe_rel',
      'label' => 'Ingredients',
      'name' => 'related_object',
      'type' => 'relationship',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => [
        'width' => '',
        'class' => '',
        'id' => '',
      ],
      'post_type' => [
        0 => 'ingredient',
      ],
      'taxonomy' => '',
      'filters' => '',
      'elements' => '',
      'min' => '',
      'max' => '',
      'return_format' => 'object',
    ],
  ],
  'location' => [
    [
      [
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'recipe',
      ],
    ],
  ],
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
]);

endif;